services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./database/db-data:/var/lib/postgresql/data
      - ./database/config/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - TZ=Europe/Warsaw

  backend:
    restart: unless-stopped
    build: ./backend
    env_file:
      - .env
    ports:
      - 8080:80

  frontend:
   build:
     context: ./frontend
   ports:
     - 3000:3000
   volumes:
     - ./frontend:/app
     - /app/node_modules
