services:
  backend:
    build: ./backend
    ports:
      - 8080:80
#
#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - 3000:3000
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules